title = "Michele Palamidessi"
baseURL = "https://palamidessi.netlify.com"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Firenze, IT"
email = "palamidessimichele@gmail.com"
favicon = "/favicon.ico"
firstName = "Michele"
lastName = "Palamidessi"
phone = "+39 328-9074402"
profileImage = "img/pala.jpg"
showEducation = true
showExperience = true
showOpenSource = false
showProjects = true
showPublications = false
showQr = false
showSkills = true
showBlog = false

[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
link = "https://www.linkedin.com/in/palamidessimichele/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/Palaxx"
name = "GitHub"


[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"